export default [
  {
    id: 'e1',
    title: 'Birthday Gift',
    amount: 94.12,
    date: new Date(2021, 7, 14),
    category: 'Other',
  },
  {
    id: 'e2',
    title: 'New TV',
    amount: 799.49,
    date: new Date(2021, 2, 12),
    category: 'Electronics',
  },
  {
    id: 'e3',
    title: 'Car Insurance',
    amount: 294.67,
    date: new Date(2021, 2, 28),
    category: 'Transport',
  },
  {
    id: 'e4',
    title: 'New Desk',
    amount: 450,
    date: new Date(2021, 5, 12),
    category: 'Furniture',
  },
  {
    id: 'e5',
    title: 'Home Rent',
    amount: 350,
    date: new Date(2021, 8, 15),
    category: 'Rent',
  },
  {
    id: 'e6',
    title: 'Pet Groom',
    amount: 50,
    date: new Date(2021, 8, 15),
    category: 'Pet',
  },
  {
    id: 'e7',
    title: 'Internet',
    amount: 50,
    date: new Date(2021, 8, 12),
    category: 'Other',
  },
  {
    id: 'e8',
    title: 'Groceries',
    amount: 100,
    date: new Date(2021, 8, 5),
    category: 'Food',
  },
];
