// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ExpenseForm from "./ExpenseForm.bs.js";

import './NewExpense.css'
;

function NewExpense(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setOpenForm = match[1];
  var onClick = function (_evt) {
    return Curry._1(setOpenForm, (function (prevState) {
                  return !prevState;
                }));
  };
  return React.createElement("div", {
              className: "new-expense"
            }, match[0] ? React.createElement(ExpenseForm.make, {}) : React.createElement("button", {
                    className: "form-button",
                    type: "button",
                    onClick: onClick
                  }, "Add New Expense"));
}

var make = NewExpense;

export {
  make ,
  
}
/*  Not a pure module */
