// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NewExpense from "./Components/NewExpense/NewExpense.bs.js";
import * as GridContainer from "./Components/UI/GridContainer.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(GridContainer.make, {
                  classes: "",
                  children: React.createElement(NewExpense.make, {})
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
