// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Demo(Props) {
  var text = Props.text;
  return React.createElement("div", undefined, text);
}

var make = Demo;

export {
  make ,
  
}
/* react Not a pure module */
