// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

import './Card.css'
;

function Card(Props) {
  var classes = Props.classes;
  var children = Props.children;
  var classesList = Belt_Option.getExn(classes);
  var htmlClasses = "card " + classesList;
  return React.createElement("div", {
              className: htmlClasses
            }, children);
}

var make = Card;

export {
  make ,
  
}
/*  Not a pure module */
