// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CardCss from "./Card.css";

function styles(prim) {
  return CardCss(prim);
}

function Card(Props) {
  var classes = Props.classes;
  var children = Props.children;
  var htmlClasses = "card " + classes;
  return React.createElement("div", {
              className: htmlClasses
            }, children);
}

var make = Card;

export {
  styles ,
  make ,
  
}
/* react Not a pure module */
